# Generated by Django 4.1.7 on 2023-03-14 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0003_rename_marchant_house_merchant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booked',
            name='house',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='booked', to='house.house'),
        ),
    ]
