# Generated by Django 4.1.7 on 2023-03-14 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0004_alter_booked_house'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to='images/houses')),
                ('address', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='house',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='house', to='house.image'),
        ),
    ]
