# Generated by Django 4.1.7 on 2023-03-14 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0005_image_house_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
