# Generated by Django 4.1.7 on 2023-03-14 23:55

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0006_house_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booked',
            name='expire_at',
        ),
        migrations.AddField(
            model_name='booked',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='expire_at',
            field=models.DateField(),
        ),
    ]
