# Generated by Django 4.1.7 on 2023-03-14 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0007_remove_booked_expire_at_booked_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='expire_at',
            field=models.DateField(),
        ),
    ]
