# Generated by Django 4.1.7 on 2023-03-15 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0010_coupon_name_alter_booked_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='coupon',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
