# Generated by Django 4.1.7 on 2023-03-15 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0011_house_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='verify',
            field=models.BooleanField(default=False),
        ),
    ]
